services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.flask
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - app-network
  
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
      - "8080:8080"
    depends_on:
      - web
    networks:
      - app-network
    restart: always
  db:
    build:
      context: .
      dockerfile: Dockerfile.mysql
    ports:
      - "3306:3306"
    networks:
      - app-network
    volumes:
      - myDB:/var/lib/mysql

networks:
  app-network:
    driver: bridge

volumes:
  myDB:

  